### ISSUE TITLE
Android app crashes when recording Screen with audio on low End Devices ( api 24+)

### ISSUE THREAD

**Issue by idzdigital** [natsuite/NatSuite-Examples#32]
App crashes while recording video along with audio. If audio recording is turned off my app runs as expected without any crash.

My set up:
Unity 2020.3.18f1
NatCorder 1.8.1
Device : Moto G4 plus ( Android 7 - API24)

In logcat we get this report:

```
E/CRASH: pid: 28042, tid: 28442, name: FMODAudioDevice
java.lang.ClassNotFoundException: android.app.servertransaction.ActivityLifecycleItem
        at java.lang.Class.classForName(Native Method)
        at java.lang.Class.forName(Class.java:400)
        at java.lang.Class.forName(Class.java:326)
        at X.0J6.A02(:132)
        at X.0Fg.A01(:256)
        at X.0eO.BC2(:42)
        at X.0Vk.run(:33)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
        at X.0Mq.run(:9)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "android.app.servertransaction.ActivityLifecycleItem" on path: DexPathList[[zip file "/system/framework/com.google.android.maps.jar", zip file "/data/app/com.instagram.android-2/base.apk", zip file "/data/app/com.instagram.android-2/split_openh264decoder.apk", zip file "/data/app/com.instagram.android-2/split_openh264encoder.apk", zip file "/data/app/com.instagram.android-2/split_pytorch.apk"],nativeLibraryDirectories=[/data/app/com.instagram.android-2/lib/arm, /data/app/com.instagram.android-2/base.apk!/lib/armeabi-v7a, /data/app/com.instagram.android-2/split_openh264decoder.apk!/lib/armeabi-v7a, /data/app/com.instagram.android-2/split_openh264encoder.apk!/lib/armeabi-v7a, /data/app/com.instagram.android-2/split_pytorch.apk!/lib/armeabi-v7a, /system/lib, /vendor/lib]]
```
How do I solve this

![image (28)](https://user-images.githubusercontent.com/39980526/141445841-20c1b34f-af5f-47e7-a07d-ba762c9866f7.png)
![image (29)](https://user-images.githubusercontent.com/39980526/141445854-b533f0de-36a2-46ea-8f38-6d2eabce85a0.png)
![image (30)](https://user-images.githubusercontent.com/39980526/141445877-bd5214e1-7883-4371-92fe-60d75b838d5b.png)
![image (31)](https://user-images.githubusercontent.com/39980526/141445895-52942a11-31fa-44ac-91a1-95f687792b49.png)

**Comment by olokobayusuf** [comment]
Can you share the full logs from app start to crash in a `.txt` attachment?

**Comment by idzdigital** [comment]
[Crash_motoG4Plus_logcat.txt](https://github.com/natsuite/NatSuite-Examples/files/7545081/Crash_motoG4Plus_logcat.txt)

**Comment by olokobayusuf** [comment]
The crash is caused by Android's internal MP4 writer implementation in `libstagefright.so`:
```
backtrace:
        #00 pc 00049c44  /system/lib/libc.so (tgkill+12) (BuildId: 18f6c9dff8601a19adcd4d73c9d6ec95)
        #01 pc 000473e3  /system/lib/libc.so (pthread_kill+34) (BuildId: 18f6c9dff8601a19adcd4d73c9d6ec95)
        #02 pc 0001d535  /system/lib/libc.so (raise+10) (BuildId: 18f6c9dff8601a19adcd4d73c9d6ec95)
        #03 pc 00019081  /system/lib/libc.so (__libc_android_abort+34) (BuildId: 18f6c9dff8601a19adcd4d73c9d6ec95)
        #04 pc 000170e4  /system/lib/libc.so (__bionic_clone) (BuildId: 18f6c9dff8601a19adcd4d73c9d6ec95)
        #05 pc 0000c3a1  /system/lib/libcutils.so (__android_log_assert+112) (BuildId: 0c56db1fa750f2183d87463b922be5be)
        #06 pc 000bdd21  /system/lib/libstagefright.so (android::MPEG4Writer::Track::writeMp4aEsdsBox()+632) (BuildId: cc562f78ffcd48cb6bd7985530d81396)
        #07 pc 000bcc8b  /system/lib/libstagefright.so (android::MPEG4Writer::Track::writeAudioFourCCBox()+374) (BuildId: cc562f78ffcd48cb6bd7985530d81396)
        #08 pc 000bcaab  /system/lib/libstagefright.so (android::MPEG4Writer::Track::writeStblBox(bool)+78) (BuildId: cc562f78ffcd48cb6bd7985530d81396)
        #09 pc 000b8239  /system/lib/libstagefright.so (android::MPEG4Writer::Track::writeTrackHeader(bool)+96) (BuildId: cc562f78ffcd48cb6bd7985530d81396)
        #10 pc 000b7987  /system/lib/libstagefright.so (android::MPEG4Writer::writeMoovBox(long long)+78) (BuildId: cc562f78ffcd48cb6bd7985530d81396)
        #11 pc 000b63cf  /system/lib/libstagefright.so (android::MPEG4Writer::reset()+1026) (BuildId: cc562f78ffcd48cb6bd7985530d81396)
        #12 pc 000d4d57  /system/lib/libstagefright.so (android::MediaMuxer::stop()+82) (BuildId: cc562f78ffcd48cb6bd7985530d81396)
        #13 pc 0002acdb  /system/lib/libmedia_jni.so (BuildId: 76e89d01f85263d9d67d62f5b8673adb)
        #14 pc 01a72605  /system/framework/arm/boot-framework.oat
```
This isn't a NatCorder bug; it's from Android itself.
